# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_custom.R or similar files

#' @name custom
#' @docType data
#' @title for internal use
'custom'
