# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# system libraries:
#   libcurl -- needed to complete setup-renv
#   libharfbuzz-dev libfribidi-dev -- needed for the textshaping package
#   Also using shinytest2 action to try running test -
# https://cran.r-project.org/web/packages/shinytest2/vignettes/use-ci.html
on:
  pull_request:
    branches: [development, dev_ejscreen2.3_shinytest2]
  push:
    branches: [dev_ejscreen2.3_shinytest2]
  
name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    name: shiny-test-automation

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
      
      - name: install needed system libs
        shell: bash
        run: |
          sudo apt install libcurl4-openssl-dev
          
      - name: Install Dependencies
        run: 
          Rscript -e 'install.packages(c("curl", "chromote", "httr", "shinytest2")))'
          
      - name: Run Shiny Tests
        run: Rscript -e 'shinytest2::test_app(".", filter="app-functionality")'

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-tests
          path: tests